POST http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTIyMTE3NDIsImlhdCI6MTU1MjIwODE0MiwibmJmIjoxNTUyMjA4MTQyLCJzdWIiOiJhY2Nlc3MiLCJpZGVudGl0eSI6InRlc3QxMjM0In0.4Vi1T-N9UDis0HnanDrwEmoDzwYDZEc3rmnhbTgNe3HD8reVdjGEgpB9cjqm_krFxBviY6oUrzoEoeS__8Mt-w
Content-Type: application/json

{
  "title": "test_title",
  "content": "test_content"
}

###